name: CI

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare code
        uses: actions/checkout@v2
      - name: Setup Ruby 2.x
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - name: Bundle install
        run: bundle install
      - name: Lint
        run: bundle exec rubocop
      - name: Test
        run: bundle exec rspec
